title: Devil
author: Devil Team
email: support@devil.ai
description: >-
  An open-source virtual assistant for Linux distributions through which we can perform various tasks with voice commands as well as key shortcuts , routines assigned by the client itself. 
baseurl: "/ubuild-jekyll" # the subpath of your site, e.g. /blog
url: "https://devil-ai.github.io" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
